<a href="https://colab.research.google.com/github/riteshkushwaha7/ML/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Np Array in Numpy

In [12]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
c=np.array([1.0,2.0,3.0,True],dtype=complex)
print(c)

[1.+0.j 2.+0.j 3.+0.j 1.+0.j]


# Arange in Numpy

In [18]:
d=np.arange(1,50,1)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [22]:
np.arange(1,51,1).reshape(10,5)
#10 row 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:

r = np.random.random((5, 5))
r = r * 100
print(np.ceil(r))


[[17. 64. 46. 92. 60.]
 [65. 18. 45. 43. 74.]
 [83. 33. 77. 68. 43.]
 [80. 90. 31. 52. 85.]
 [39.  5.  9. 86. 80.]]


In [34]:
np.linspace(-8,10,20) #lower range, upper range, linerly seperable points(equi distant)

array([-8.        , -7.05263158, -6.10526316, -5.15789474, -4.21052632,
       -3.26315789, -2.31578947, -1.36842105, -0.42105263,  0.52631579,
        1.47368421,  2.42105263,  3.36842105,  4.31578947,  5.26315789,
        6.21052632,  7.15789474,  8.10526316,  9.05263158, 10.        ])

In [42]:
k = np.identity(4)  #identity matrix
k

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
#dimensions/shape/size/itemsize
print(k.ndim)
print(k.shape)
print(k.size)
print(k.itemsize) #default 8bypte(int64)

2
(4, 4)
16
8


# Changing Datatype

In [53]:
k=k.astype(np.int32)
print(k)
k.itemsize #size changed

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


4

# Array Operations

In [66]:
a1=np.arange(1,13).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
#scaler operations a1**2 a1/2 a1+5 a1-2
a2/2

array([[ 6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. ],
       [10.5, 11. , 11.5]])

In [60]:
#vector operations
a1+a2

array([[13, 15, 17, 19],
       [21, 23, 25, 27],
       [29, 31, 33, 35]])

In [68]:
a1@a2 #dot product a*p @ p*b = a*b

array([[180, 190, 200],
       [444, 470, 496],
       [708, 750, 792]])

In [69]:
a1*a1 #hadamard product a*p * a*p = a*p element wise multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [64]:
a1**a2

array([[                   1,                 8192,              4782969,
                  1073741824],
       [        152587890625,       16926659444736,     1628413597910449,
          144115188075855872],
       [-6289078614652622815,  3875820019684212736, -2732210440490168087,
        -5038753926841630720]])