<a href="https://colab.research.google.com/github/riteshkushwaha7/ML/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Np Array in Numpy

In [3]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
c=np.array([1.0,2.0,3.0,True],dtype=complex)
print(c)

[1.+0.j 2.+0.j 3.+0.j 1.+0.j]


# Arange in Numpy

In [6]:
d=np.arange(1,50,1)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [7]:
np.arange(1,51,1).reshape(10,5)
#10 row 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:

r = np.random.random((5, 5))
r = r * 100
print(np.ceil(r))


[[66.  9. 14. 69. 93.]
 [ 1.  2. 10. 34. 28.]
 [ 3. 52. 38. 93. 52.]
 [23. 32.  9. 88. 41.]
 [18. 65. 74. 91. 13.]]


In [11]:
np.linspace(-8,10,20) #lower range, upper range, linerly seperable points(equi distant)

array([-8.        , -7.05263158, -6.10526316, -5.15789474, -4.21052632,
       -3.26315789, -2.31578947, -1.36842105, -0.42105263,  0.52631579,
        1.47368421,  2.42105263,  3.36842105,  4.31578947,  5.26315789,
        6.21052632,  7.15789474,  8.10526316,  9.05263158, 10.        ])

In [12]:
k = np.identity(4)  #identity matrix
k

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#dimensions/shape/size/itemsize
print(k.ndim)
print(k.shape)
print(k.size)
print(k.itemsize) #default 8bypte(int64)

2
(4, 4)
16
8


# Changing Datatype

In [14]:
k=k.astype(np.int32)
print(k)
k.itemsize #size changed

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


4

# Array Operations

In [15]:
a1=np.arange(1,13).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
#scaler operations a1**2 a1/2 a1+5 a1-2
a2/2

array([[ 6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. ],
       [10.5, 11. , 11.5]])

In [16]:
#vector operations
a1+a2

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [17]:
a1@a2 #dot product a*p @ p*b = a*b

array([[180, 190, 200],
       [444, 470, 496],
       [708, 750, 792]])

In [18]:
a1*a1 #hadamard product a*p * a*p = a*p element wise multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [19]:
a1**a2

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

# Array Functions

In [21]:
#min/max/prod/sum
np.max(a1)

np.int64(12)

In [22]:
np.max(a1,axis=0) #0-> col and 1-> row

array([ 9, 10, 11, 12])

In [26]:
#means/median/std/var
print(np.mean(a1))
print(np.std(a1))
print(np.median(a1))
print(np.var(a1))

6.5
3.452052529534663
6.5
11.916666666666666


In [28]:
#trignometric
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

In [29]:
#logarithmic
np.log(a1)


array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [30]:
np.exp(a1)
#exponent

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [33]:
np.round(np.random.random((2,3))*100)
#round

array([[45.,  6., 20.],
       [ 9., 48., 86.]])

In [34]:
np.floor(np.random.random((2,3))*100)
#floor

array([[31., 84., 59.],
       [71., 17., 70.]])

In [35]:
np.ceil(np.random.random((2,3))*100)
#ceil

array([[36., 73., 86.],
       [79., 98., 35.]])

# Indexing and Slicing


In [39]:
a1[0,1]

np.int64(2)

In [45]:
a1[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

# NDArray Iteration

In [47]:
a2


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [48]:
for i in np.nditer(a2):
  print(i)

12
13
14
15
16
17
18
19
20
21
22
23


# Reshaping

In [50]:
np.transpose(a2)

array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

In [52]:
a2.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [53]:
a2.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# Stacking

In [58]:
a3=np.arange(12).reshape(4,3)
a4=np.arange(12,24).reshape(4,3)
np.hstack((a3,a4)) #shape same hona chahiye

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [60]:
np.vstack((a3,a4,a3)) #shape same hona chahiye

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Splitting

In [62]:
np.vsplit(a4,4) #similiary for hsplit

[array([[12, 13, 14]]),
 array([[15, 16, 17]]),
 array([[18, 19, 20]]),
 array([[21, 22, 23]])]